- id: scan4secrets
  name: scan4secrets
  description: Block commits containing secrets
  entry: scan4secrets --path .
  args: ["--report", "json", "--output", ".scan4secrets-report", "--fail-on", "high", "--quiet"]
  language: python
  types: [text]
  pass_filenames: false
