"""HTML report v2: severity badges, sortable, filterable."""

import html as _h
from pathlib import Path
from typing import List
from collections import Counter

from scan4secrets.engine.findings import Finding


_BADGE = {
    "critical": "#dc2626", "high": "#ea580c", "medium": "#ca8a04",
    "low": "#0891b2", "info": "#475569",
}

_TEMPLATE = """<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"/>
<title>scan4secrets report</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font-family: -apple-system, system-ui, sans-serif; margin: 0; padding: 2rem; background: #0b1020; color: #e5e7eb; }}
  h1 {{ font-size: 1.5rem; margin: 0 0 1rem; }}
  .meta {{ color: #9ca3af; font-size: 0.875rem; margin-bottom: 1rem; }}
  .summary {{ display: flex; gap: 0.5rem; margin: 1rem 0; flex-wrap: wrap; }}
  .pill {{ padding: 0.4rem 0.8rem; border-radius: 999px; font-size: 0.85rem; color: white; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 0.9rem; background: #111827; }}
  th, td {{ text-align: left; padding: 0.6rem 0.8rem; border-bottom: 1px solid #1f2937; }}
  th {{ background: #1e293b; cursor: pointer; user-select: none; position: sticky; top: 0; }}
  tr:hover {{ background: #0f172a; }}
  .sev {{ display: inline-block; padding: 0.15rem 0.55rem; border-radius: 4px; color: white; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; }}
  .verified-true {{ color: #22c55e; font-weight: 600; }}
  .verified-false {{ color: #94a3b8; }}
  code {{ background: #0f172a; padding: 0.1rem 0.4rem; border-radius: 3px; font-size: 0.85rem; word-break: break-all; }}
  input[type=text] {{ background: #1e293b; color: white; border: 1px solid #334155; padding: 0.5rem; border-radius: 4px; width: 300px; margin-bottom: 1rem; }}
</style>
</head><body>
<h1>scan4secrets report</h1>
<div class="meta">{total} findings &middot; generated by scan4secrets v2</div>
<div class="summary">{pills}</div>
<input type="text" id="filter" placeholder="filter (rule, file, severity)..."/>
<table id="t">
  <thead><tr>
    <th data-col="severity">Severity</th>
    <th data-col="rule_id">Rule</th>
    <th data-col="verified">Verified</th>
    <th data-col="file">File</th>
    <th data-col="line">Line</th>
    <th data-col="value">Secret (redacted)</th>
    <th data-col="entropy">Entropy</th>
  </tr></thead>
  <tbody>
{rows}
  </tbody>
</table>
<script>
  const tbl = document.getElementById("t");
  const tbody = tbl.tBodies[0];
  const inp = document.getElementById("filter");
  inp.addEventListener("input", () => {{
    const q = inp.value.toLowerCase();
    for (const tr of tbody.rows) {{
      tr.style.display = tr.textContent.toLowerCase().includes(q) ? "" : "none";
    }}
  }});
  for (const th of tbl.tHead.rows[0].cells) {{
    th.addEventListener("click", () => {{
      const idx = th.cellIndex;
      const rows = Array.from(tbody.rows);
      const asc = th.dataset.asc !== "1";
      rows.sort((a, b) => {{
        const av = a.cells[idx].textContent.trim();
        const bv = b.cells[idx].textContent.trim();
        const num = parseFloat(av) - parseFloat(bv);
        return asc ? (isNaN(num) ? av.localeCompare(bv) : num) : (isNaN(num) ? bv.localeCompare(av) : -num);
      }});
      for (const r of rows) tbody.appendChild(r);
      th.dataset.asc = asc ? "1" : "0";
    }});
  }}
</script>
</body></html>"""


def _row(f: Finding, unsafe_show: bool) -> str:
    secret = _h.escape(f.secret if unsafe_show else f.secret_redacted)
    sev = f.severity
    color = _BADGE.get(sev, "#475569")
    vmark = (
        f"<span class='verified-true'>YES</span>" if f.verified is True
        else f"<span class='verified-false'>no</span>" if f.verified is False
        else "&mdash;"
    )
    return (
        f"<tr>"
        f"<td><span class='sev' style='background:{color}'>{sev}</span></td>"
        f"<td><code>{_h.escape(f.rule_id)}</code></td>"
        f"<td>{vmark}</td>"
        f"<td>{_h.escape(f.file)}</td>"
        f"<td>{f.line}</td>"
        f"<td><code>{secret}</code></td>"
        f"<td>{f.entropy}</td>"
        f"</tr>"
    )


def write(findings: List[Finding], path: Path, *, unsafe_show: bool = False):
    counts = Counter(f.severity for f in findings)
    pills = "".join(
        f"<span class='pill' style='background:{_BADGE.get(s,'#475569')}'>{s}: {counts.get(s,0)}</span>"
        for s in ("critical", "high", "medium", "low", "info")
    )
    rows = "\n".join(_row(f, unsafe_show) for f in findings)
    path.write_text(_TEMPLATE.format(total=len(findings), pills=pills, rows=rows))
